shared:
  image: maven:3-adoptopenjdk-8

jobs:
  pr:
    requires: [~pr]
    steps:
      - run_arbitrary_script: apt-get update && apt-get install autoconf make python -y && mvn clean test --quiet
  main:
    requires: [~commit]
    steps:
      - run_arbitrary_script: apt-get update && apt-get install autoconf make python -y && mvn clean deploy -q --settings settings.xml && mvn install -Dmaven.test.skip=true -Pdocker --settings settings_docker.xml;
    secrets:
      - CI_DEPLOY_USERNAME
      - CI_DEPLOY_PASSWORD
      - DOCKER_EMAIL
      - DOCKER_REPO
      - DOCKER_PASSWORD
      - DOCKER_REPOSITORY
      - DOCKER_USERNAME
    annotations:
      screwdriver.cd/dockerEnabled: true
      screwdriver.cd/ram: TURBO
      screwdriver.cd/dockerRam: TURBO