shared:
  image: maven:3-adoptopenjdk-8

jobs:
  main:
    requires: [~pr, ~commit]
    timeout: 180
    steps:
      - run_arbitrary_script: apt-get update && apt-get install autoconf make python -y && ./build.sh pom.xml && mvn clean test --quiet
