#!/bin/sh
set -e

case "$1" in
    remove)
        # Remove logs
        rm -rf /var/log/opentsdb
        
        # remove **only** empty data dir
        rmdir -p --ignore-fail-on-non-empty /tmp/opentsdb
    ;;

    purge)
    	# Remove service
        update-rc.d opentsdb remove >/dev/null || true
    
        # Remove logs and data
        rm -rf /var/log/opentsdb /tmp/opentsdb

        # Remove user/group
        deluser opentsdb || true
        delgroup opentsdb || true
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Nothing to do here
    ;;

    *)
        echo "$0 called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac
