#!/bin/bash

set -e
me=${0##*/}
mydir=`dirname "$0"`
for make in $MAKE make gmake; do
  # Try to weed out BSD make and such (they don't support those flags).
  $make --version --quiet >/dev/null 2>&1 && break
done
CLASSPATH=`$make --quiet -C $(dirname "$mydir") printcp` || {
  echo >&2 "$make returned $?"
  echo >&2 'Please make sure you have GNU make installed in your PATH'
  exit 42
}

usage() {
  echo >&2 "usage: $me <command> [args]"
  echo 'Valid commands: import, query, tsd, scan, uid'
  exit 1
}

case $1 in
  (import)
    MAINCLASS=TextImporter
    ;;
  (query)
    MAINCLASS=CliQuery
    ;;
  (tsd)
    MAINCLASS=TSDMain
    ;;
  (scan)
    MAINCLASS=DumpSeries
    ;;
  (uid)
    MAINCLASS=UidManager
    ;;
  (*)
    echo >&2 "$me: error: unknown command '$1'"
    usage
    ;;
esac
shift

JAVA=${JAVA-'java'}
JVMARGS=${JVMARGS-'-enableassertions -enablesystemassertions'}
test -r "$mydir/tsdb.local" && . "$mydir/tsdb.local"
exec $JAVA $JVMARGS -classpath "$CLASSPATH" net.opentsdb.tools.$MAINCLASS "$@"
